# SPDX-License-Identifier: GPL-2.0
#
# Ky Clock specific Makefile
#
#SoC support
obj-$(CONFIG_KY_K1PRO_CCU) += ccu-k1pro.o ccu-pll-k1pro.o
obj-$(CONFIG_KY_X1_CCU) += ccu-x1.o ccu_mix.o
obj-$(CONFIG_$(SPL_TPL_)KY_X1_CCU) += ccu_ddn.o ccu_pll.o
