# SPDX-License-Identifier: GPL-2.0

ifdef CONFIG_VIDEO_KY
obj-y += dsi/
obj-y += ky_dpu.o
obj-$(CONFIG_DISPLAY_KY_HDMI) += ky_hdmi.o
obj-$(CONFIG_DISPLAY_KY_MIPI) += ky_mipi.o
obj-$(CONFIG_DISPLAY_KY_EDP) += ky_edp.o

endif
