# SPDX-License-Identifier: GPL-2.0

obj-y += video/ky_video_tx.o \
		video/ky_mipi_port.o \
		drv/ky_dphy.o \
		drv/ky_dsi_common.o \
		drv/ky_dsi_drv.o

obj-y += video/lcd/lcd_icnl9911c.o
obj-y += video/lcd/lcd_icnl9951r.o
obj-y += video/lcd/lcd_jd9365dah3.o
obj-y += video/lcd/lcd_gx09inx101.o
obj-y += video/lcd/lcd_lt8911ext_edp_1080p.o

